Exercises for configuration chapter
merely-useful/py-rse pull request #456
Opened 2020-08-30 11:47 UTC by gvwilson

2020-08-30 22:48 UTC, DamienIrving commented on chapters/config.Rmd
>      that reads settings from a file.
I'm a little confused by "an option that writes all of its settings to a file that reads settings from a file". Would you be able to write out the solution (see comment in the solutions file below)?

2020-08-30 22:53 UTC, DamienIrving commented on chapters/solutions.Rmd
> +FIXME
Would you be able to add the solution here? It needs to build on the repo version of [`plotcounts.py`](https://github.com/merely-useful/merely-useful.github.io/blob/book/zipf/bin/plotcounts.py`).

2020-08-30 22:55 UTC, DamienIrving requested changes
Thanks, @gvwilson. I've added a commit to this branch with updates to the exercise and solution about updating `Makefile`, because it involved a new concept that wasn't introduced in the automation chapter (the text manipulation function `word`).

Would you be able to add solutions for the other exercises? (I added a comment about doing this for one of the exercises, but I actually think it needs to be done for all.) It's hard to review the appropriateness of a new exercise without seeing what you think the solution should be.

2020-09-10 01:23 UTC, DamienIrving commented
@gvwilson Was this PR closed by mistake? The updates I added to the exercise and solution about the `Makefile` definitely need to be merged, and if you don't want to figure out solutions for the other exercises now we could merge and come back to the solutions later?

2020-09-10 11:56 UTC, gvwilson commented
?? I thought I merged this one, including your changes ??

2020-09-11 22:24 UTC, DamienIrving commented
@gvwilson Not sure what happened. Anyway, we should fill in the solutions before merging. I'll hopefully have time to work on them this weekend.

2020-09-12 08:52 UTC, lwjohnst86 approved these changes

2020-09-12 08:52 UTC, merged